import Link from "next/link";
export const metadata = { title: "Privacy" };
export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl px-6 py-14"><Link href="/" className="text-primary">← HireKarlo</Link><h1 className="mt-8 text-3xl font-bold">Privacy notice</h1><p className="mt-3 text-sm text-muted-foreground">Updated September 16, 2026. Operator: Aman Samani. Contact: <a className="underline" href="mailto:amanworkinfo@gmail.com">amanworkinfo@gmail.com</a>.</p><div className="mt-8 space-y-7 leading-7">
    <section><h2 className="text-xl font-semibold">Information we process</h2><p className="mt-2">Recruiter account details, organization memberships, job postings, candidate contact details and resumes, applications, interview feedback, activity records, and billing identifiers support the recruitment service. We store password hashes. Payment card details are collected by the payment provider rather than stored by HireKarlo.</p></section>
    <section><h2 className="text-xl font-semibold">Recruitment data</h2><p className="mt-2">The company or recruitment agency collecting an application decides how to use the information for hiring. Contact that organization for questions about its hiring process. You may also contact Aman for help with access, correction, export, or deletion requests. We verify requests before acting on them.</p></section>
    <section><h2 className="text-xl font-semibold">Service providers and AI</h2><p className="mt-2">HireKarlo uses Vercel for hosting, PostgreSQL for records, Cloudinary for resumes, an email service for notifications, and Google Gemini for optional AI screening. Resume text and job descriptions may be sent to Google to produce a match score and summary. AI output is advisory and can be inaccurate. The recruiting organization must explain its use of AI and review candidates itself. Provider terms and account settings determine processing locations and AI data handling.</p></section>
    <section><h2 className="text-xl font-semibold">Retention and security</h2><p className="mt-2">Records remain available while an organization uses HireKarlo; archiving a job retains its application history. Trial expiry does not automatically erase records. Unused temporary resume uploads are scheduled for cleanup. Deletion requests are handled through support, including associated file storage and applicable backup retention. Contact us for the current retention arrangements before uploading production candidate data.</p></section>
    <section><h2 className="text-xl font-semibold">Cookies and analytics</h2><p className="mt-2">Essential authentication and workspace cookies support the service. Optional Vercel analytics loads after you accept it; you can change that choice using Cookie settings. See the <Link className="underline" href="/cookies">cookie notice</Link>.</p></section>
    <section><h2 className="text-xl font-semibold">Contact and changes</h2><p className="mt-2">Send privacy questions to amanworkinfo@gmail.com. Material changes will be reflected in this notice. Customers should request the service agreement, processing terms, and provider details needed for their own jurisdiction before a production rollout.</p></section>
  </div></main>;
}
