import Link from "next/link";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, CalendarDays, Check, Fingerprint, Layers3, MoveUpRight, SearchCheck, Sparkles, Users } from "lucide-react";
import LandingMotion from "@/components/landing/landing-motion";
import WorkflowPreview from "@/components/landing/workflow-preview";

const features = [
  { icon: BriefcaseBusiness, number: "01", title: "A home for every opening.", text: "Create a role, choose your interview stages and share a public application link. Keep incoming applications connected to the right job." },
  { icon: Sparkles, number: "02", title: "More context. Better reviews.", text: "Bring resumes, candidate profiles and optional AI screening into the same view. Let your team make an informed, human decision." },
  { icon: CalendarDays, number: "03", title: "A team that stays in sync.", text: "Assign interviewers, schedule conversations and capture scorecards. Stop losing the details between a good interview and the next step." },
];

export default function Home() {
  return <LandingMotion>
    <a href="#content" className="skip-link rounded-lg bg-primary px-4 py-3 text-primary-foreground">Skip to content</a>
    <header className="marketing-section flex min-h-24 items-center justify-between gap-4 border-b border-white/10">
      <Link href="/" className="flex items-center gap-2.5 text-xl font-semibold tracking-tight" aria-label="HireKarlo home"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground">h.</span>HireKarlo<span className="text-primary">.</span></Link>
      <nav className="motion-nav hidden items-center gap-7 text-xs text-muted-foreground md:flex" aria-label="Product navigation"><a href="#workflow" className="hover:text-white">The workflow</a><a href="#features" className="hover:text-white">Why HireKarlo</a><Link href="/pricing" className="hover:text-white">Plans</Link><Link href="/track" className="hover:text-white">Track application</Link></nav>
      <div className="flex items-center gap-4"><Link href="/login" className="text-xs text-muted-foreground hover:text-white">Log in</Link><Link href="/register" className="hidden min-h-10 items-center gap-2 rounded-full border border-white/20 px-5 text-xs font-medium transition-colors hover:bg-white/5 sm:inline-flex">Get started<ArrowUpRight className="size-3.5" aria-hidden="true"/></Link></div>
    </header>
    <main id="content">
      <section className="marketing-section landing-hero relative pb-14 pt-16 sm:pb-20 sm:pt-24">
        <div className="pointer-events-none absolute inset-0 hero-grid opacity-30" aria-hidden="true"/><div className="hero-ambient" aria-hidden="true"/>
        <div className="relative grid gap-10 lg:grid-cols-[1.5fr_1fr] lg:items-end lg:gap-20">
          <div><p className="hero-intro eyebrow flex items-center gap-2"><span className="size-1.5 rounded-full bg-primary"/>Thoughtful hiring starts here</p><h1 className="mt-7 max-w-3xl text-[clamp(3.2rem,7.4vw,6.7rem)] font-medium leading-[1.02] tracking-[-.065em]"><span className="hero-line"><span>Great people.</span></span><span className="hero-line"><span>Less <span className="text-primary">process.</span></span></span></h1></div>
          <div className="hero-copy lg:pb-2"><p className="max-w-md text-base leading-8 text-[#a9afa3] sm:text-lg">From the first application to the final decision. One calm workspace for your entire hiring team.</p><div className="mt-7 flex flex-wrap items-center gap-4"><Link href="/register" className="motion-cta group inline-flex min-h-12 items-center gap-7 rounded-full bg-primary px-6 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90">Create your workspace<ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" aria-hidden="true"/></Link><a href="#workflow" className="inline-flex min-h-11 items-center gap-2 text-sm text-foreground/80 hover:text-primary">Explore the workflow<ArrowRight className="size-4" aria-hidden="true"/></a></div><p className="mt-5 text-[11px] text-muted-foreground">14-day trial · No automatic charge at trial expiry</p></div>
        </div>
        <div data-reveal="120" className="mt-14 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-[11px] tracking-wide text-muted-foreground">{["Built for in-house teams", "Ready for recruitment agencies", "Human decisions, always"].map(text => <span className="flex items-center gap-2" key={text}><Check className="size-3.5 text-primary" aria-hidden="true"/>{text}</span>)}</div>
      </section>
      <section data-reveal="0" id="workflow" className="marketing-section scroll-mt-8 pb-20 sm:pb-28"><WorkflowPreview/></section>
      <section id="features" className="border-y border-white/10 bg-[#171a15] py-20 sm:py-24">
        <div className="marketing-section"><div data-reveal="0" className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Made for the work that matters</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-tight tracking-[-.045em] sm:text-5xl">Less chasing updates.<br/><span className="text-[#8b9482]">More moving forward.</span></h2></div><p className="max-w-xs text-sm leading-7 text-muted-foreground">Your pipeline, your people and your next steps. Connected from the beginning.</p></div>
          <div className="mt-14 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, number, title, text }, index) => <article key={number} data-reveal={index * 90} data-spotlight className="motion-card group rounded-2xl border border-white/10 bg-[#11140f] p-7 transition-colors hover:border-primary/30"><div className="mb-12 flex items-center justify-between"><Icon className="size-6 text-primary" strokeWidth={1.4} aria-hidden="true"/><span className="font-mono text-xs text-muted-foreground">/{number}</span></div><h3 className="text-xl font-medium tracking-tight">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{text}</p></article>)}</div>
        </div>
      </section>
      <section data-reveal="0" className="marketing-section grid gap-12 py-20 lg:grid-cols-2 lg:gap-24 lg:py-28">
        <div><p className="eyebrow">Clarity at every level</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-.045em] sm:text-5xl">Your process.<br/>A shared perspective.</h2><p className="mt-6 max-w-md text-sm leading-7 text-muted-foreground">A growing team needs more than a spreadsheet. HireKarlo gives everyone the context to do their part, with access shaped around their role.</p><Link href="/pricing" className="mt-7 inline-flex items-center gap-3 border-b border-primary/40 pb-2 text-sm text-primary">Find your workspace plan<MoveUpRight className="size-4" aria-hidden="true"/></Link></div>
        <div className="space-y-2">{[{ icon: Layers3, title: "One workspace, organized", text: "Jobs, candidate records and agency clients stay connected within their organization." },{ icon: Users, title: "The right people in the room", text: "Owners, admins, recruiters and interviewers each have defined permissions." },{ icon: Fingerprint, title: "A history you can follow", text: "Review recorded workspace changes in audit history and track plan usage in billing." }].map(({ icon: Icon, title, text }) => <div key={title} className="motion-detail flex gap-5 border-b border-white/10 py-6"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-white/10"><Icon className="size-5 text-primary" strokeWidth={1.5} aria-hidden="true"/></div><div><h3 className="text-base font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div>
      </section>
      <section data-reveal="0" className="marketing-section pb-20"><div className="relative overflow-hidden rounded-3xl bg-[#d4efb0] px-6 py-12 text-[#182111] sm:px-12 sm:py-16"><div className="grid gap-9 md:grid-cols-[1.5fr_1fr] md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em]">Make room for your next great hire</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-[1.12] tracking-[-.05em] sm:text-6xl">Build a team.<br/>Enjoy the process.</h2></div><div><Link href="/register" className="motion-cta inline-flex min-h-12 items-center justify-between gap-12 rounded-full bg-[#182111] px-6 text-sm font-medium text-white hover:bg-[#293b1c]">Get started<ArrowUpRight className="size-4" aria-hidden="true"/></Link><Link href="/track" className="mt-6 flex items-center gap-2 text-xs"><SearchCheck className="size-4" aria-hidden="true"/>Already applied? Track your application</Link></div></div></div></section>
    </main>
    <footer className="marketing-section border-t border-white/10 py-8"><div className="flex flex-col justify-between gap-6 sm:flex-row"><div><p className="text-lg font-semibold tracking-tight">HireKarlo<span className="text-primary">.</span></p><p className="mt-2 text-xs text-muted-foreground">Built by Aman Samani. A personal SaaS portfolio project.</p></div><nav aria-label="Footer" className="flex max-w-md flex-wrap items-center gap-x-6 gap-y-3 text-xs text-muted-foreground">{[["Plans","/pricing"],["Track application","/track"],["Terms","/terms"],["Privacy","/privacy"],["Cookies","/cookies"]].map(([label,href]) => <Link key={href} href={href} className="hover:text-white">{label}</Link>)}</nav></div></footer>
  </LandingMotion>;
}
