import Link from "next/link";
export const metadata = { title: "Terms" };
export default function TermsPage() {
  return <main className="mx-auto max-w-3xl px-6 py-14"><Link href="/" className="text-primary">← HireKarlo</Link><h1 className="mt-8 text-3xl font-bold">Service terms</h1><p className="mt-3 text-sm text-muted-foreground">Updated September 16, 2026. HireKarlo is operated by Aman Samani. Support: amanworkinfo@gmail.com.</p><div className="mt-8 space-y-7 leading-7">
    <section><h2 className="text-xl font-semibold">Business use</h2><p className="mt-2">HireKarlo provides recruitment workflow software for companies and agencies. Account holders must have authority to act for their organization and upload its recruitment data. Keep account credentials secure and invite only authorized team members.</p></section>
    <section><h2 className="text-xl font-semibold">Trial, plans, and payment</h2><p className="mt-2">A 14-day trial provides the limits shown on the pricing page, with no automatic payment at expiry. A paid subscription begins after provider verification. Plans renew monthly until canceled through the billing portal. Prices and tax information appear at checkout. Usage limits apply per organization; excess usage is blocked without automatic overage charges. Failed AI attempts can consume credits. Existing data remains available to authorized recruiters for review and export after plan expiry.</p></section>
    <section><h2 className="text-xl font-semibold">Cancellation and support</h2><p className="mt-2">Cancel renewal through the billing portal or contact support if the portal is unavailable. A cancellation scheduled for period end retains access until that period ends. Contact support about duplicate charges, service faults, refunds, data exports, or deletion; any mandatory consumer or other legal rights remain applicable.</p></section>
    <section><h2 className="text-xl font-semibold">Candidate data and AI</h2><p className="mt-2">Customers are responsible for their hiring notices, lawful processing, permissions, and employment decisions. Do not use AI scores as an automatic hiring or rejection decision. Customers retain ownership of their uploaded material and permit processing needed to deliver the service.</p></section>
    <section><h2 className="text-xl font-semibold">Acceptable use and availability</h2><p className="mt-2">Do not upload malware, send spam, bypass usage limits, access other organizations&apos; records, or use the service unlawfully. Accounts may be restricted to protect the service or investigate misuse. Availability depends partly on hosting and external providers; these public plans include no contractual uptime guarantee.</p></section>
    <section><h2 className="text-xl font-semibold">Contact</h2><p className="mt-2">Contact <a className="underline" href="mailto:amanworkinfo@gmail.com">amanworkinfo@gmail.com</a> for commercial agreements and onboarding. Organizations needing specific processing terms or service commitments should agree those before deployment. See <Link className="underline" href="/privacy">Privacy</Link> and <Link className="underline" href="/pricing">Pricing</Link>.</p></section>
  </div></main>;
}
